### ISSUE TITLE
Last action repeat counts as failed loop

### ISSUE THREAD

**Issue by richardhussey** [omsi6/omsi6.github.io#53]
I use "Pause on failed loop" to find when a change I have made to my action list result in a list that cannot be completed, rather than as a method of pausing at the end of runs.

The following circumstances appear to count as a 'failed loop', when that would not seem to me to count!  This therefore has the same functionality as "Pause before restart" in every circumstance that I have experienced.

+ "Pause on failed loop" - Checked
+ "Repeat last action on list" - Checked
+ Specified number of actions completed - I.e. if last action is to be completed 3 times, then it has been completed at least three times
+ Last use of that action does not complete because mana runs out

My suggestion would be that as long as item three is satisfied (i.e. the minimum number of repeats have been completed) that this doesn't count as a failed run.

Alternative solution - tooltip to specify what a 'failed loop' actually counts as.

**Comment by super-aardvark** [comment]
This has been bothering me for a while, and I finally came here to suggest it... lo and behold, someone beat me to it by just a few hours.

So I started looking into implementing it, and... based on the code, and my testing, there's literally no difference between "Pause on failed loop" and "Pause before restart".  They both pause the game on any restart.  Is your experience different?

**Comment by omsi6** [comment]
Fixed in 336754747300a2d3ef049bb49294bd8fd4f16fd3. Thanks for the report!
