### ISSUE TITLE
BETA - Restoration and Spatiomancy should not be 100% Int based

### ISSUE THREAD

**Issue by HFHG-DELTA** [omsi6/omsi6.github.io#70]
**Describe the issue**
Restoration and Spatiomancy are currently set as 100% Int .
This causes the Intelligence stat to massively compound and raise the Intelligence Talent far too quickly (45k to 100k in 12 hours).
Restoration and Spatiomancy actions are also then taken too inexpensively (Spatiomancy skill 146 to 1302 in 12 hours).

See attached pictures.

Additionally,
The Wizard College Bonus directly divides the mana cost of both actions (30,000 mana) and makes this issue even worse. The bonus was approx 3x in pictures and reduced the actions to 10,000 mana (30k/3) even before the 100% Int impact.

**Describe the solution you'd like**
Restoration and Spatiomancy should be watered down and have other stats contributing to them.
Chronomancy and Pyromancy used Speed and Perception. Other stats could be associated with the 2 new magics.

Restoration: (???) 30%, Int 60%, Soul 10%
Spatiomancy: (???) 30%, Int 60%, Soul 10%

Wizard College Bonus benefit reduced or modified in impact somehow.

**Describe alternatives you've considered**

Remove the Wizard College Bonus and have Wizard College simply increase the Magic skill for now.

Remove the 200% Exp multiplier. 

**Additional context**

(Sidenote: The Predictor mana values for Spatiomancy in the pictures are incorrect. I haven't been able to get those to calculate properly on Predictor yet.)

Current Magicks
Chronomancy: Spd 30%, Int 60% Soul 10%
Pyromancy: Per 20%, Int 70%, Soul 10%
Practical Magic: Con 20%, Per 30%, Int 50%
Dark Magic: Con 20%, Int 50%, Soul 30%

![Spaciomancy INT inflation 1](https://user-images.githubusercontent.com/98241233/150701751-e22a1b2b-ab10-47da-a6e3-b9e681b66201.PNG)
![Spaciomancy INT inflation 2](https://user-images.githubusercontent.com/98241233/150701752-e34c65d2-57b2-44b8-bfb1-36a17874abc0.PNG)

**Comment by omsi6** [comment]
I've applied some nerfs and changes, let me know if they're good.

**Comment by HFHG-DELTA** [comment]
The action stats being spread out and exp multiplier look much better right now. I can't yet tell until the next fix (below) though.


**New Issue:**
**Describe the issue**
The Restoration and Spatiomancy action's mana costs are now too high. 
I'm going to compare Restoration to Pyromancy here.

An optimized run at around 1 hour and 40 minutes will get 44k Pyromancy actions or 8k Restoration actions. (see attached.)


**Describe the solution you'd like**
Probably the original mana cost of Restoration decreased.

I'm not sure what the sweet spot is for Restoration. In the form Restoration takes right now (increase Self Combat 2x as effectively as Combat skill), it should probably be somewhere between 1x to 3x as expensive as Pyromancy (after Z5 benefits).  

Decreasing the original cost of Restoration is probably the easiest method for this. There are additional factors to consider though.

**Describe alternatives you've considered**
Increasing the benefit of Wizard College could be done, but I personally. don't like the Wizard College mechanic in the first place.

A lot of this depends on whether The Spire is implemented and whether Restoration continues working the same way as it currently does.

If The Spire is implemented, then players need bigger numbers and Restoration becomes very important. If the Large Dungeon is still the only place where combat is used, then Restoration is a cherry on top of the cake and should be expensive.

If Restoration is changed to modify _Team Combat_ instead of Self Combat as its description currently says, then it should be very costly to obtain.



**Additional context**
Z5 adds a lot of mana to a run via 50x Accept Donations, 10x Sell Artifact, Tidy Up, and potentially the house taxation if that's ever implemented. 
Spatiomancy skill benefits Pryo and Resto equally in the long run.

Restoration increasing Team Combat instead of Self Combat would only make sense mathematically if The Spire is implemented. I did some math before and the benefit of Restoration increasing Team Combat by 2x the rate that Combat does is very powerful.

![Restoration - 8k actions over 1 hour 49 minutes](https://user-images.githubusercontent.com/98241233/150854120-c0208d9f-615e-459e-bfbc-73ebcf41584f.PNG)
![Pyromancy - 44k actions over 1 hour 40 minutes](https://user-images.githubusercontent.com/98241233/150854123-d36c819f-1c10-4742-a742-64c4f4ffc3bd.png)

**Comment by omsi6** [comment]
I think this is in a fine state now.
