### ISSUE TITLE
[heirlooms] Equipped heirloom not (always) shown

### ISSUE THREAD

**Issue by jasperfirecai2** [omsi6/omsi6.github.io#77]
**Describe the bug**
When loading a save, all carried heirlooms are shown but not all the equipped ones are. 

**To Reproduce**
1. Have a save with equipped and carrier heirlooms
2. Load it into the heirloom tool
3. In certain configurations your equipped staff, core and/or shield will not show in the list of heirlooms
4. Swap equipped heirloom with a carried one
5. Now the newly equipped is gone but the swapped out one is available

**Expected behavior**
The tool to show all equipped or carried heirlooms.

**Screenshots**
![image](https://user-images.githubusercontent.com/8398131/179273809-42623a77-bb13-426c-9f6d-263d19c73457.png)
![image](https://user-images.githubusercontent.com/8398131/179273831-652d4096-e2bb-4950-aa63-e18d77116321.png)

**Savefile**
(https://pastebin.com/EY6diMxd)

**Additional context**
This didn't use to happen, maybe a game update changed things, maybe because i'm on Steam?

**Comment by jasperfirecai2** [comment]
It seems that when unselecting an heirloom from the box, it will show the equipped loom. Sorry if this is mislabelled as a bug, but the equipped loom would be nice to see in the list

**Comment by omsi6** [comment]
I think the current behavior is fine. To clarify the current behavior: if unselected, it shows equipped (which is the default state), and when unselecting a list item, it shows again. It also saves selections through refreshes.
